# Generated by Django 5.0.4 on 2024-04-17 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_type', models.CharField(choices=[('Staff', 'Staff'), ('Student', 'Student'), ('Visitor', 'Visitor')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CBSESchool',
            fields=[
                ('SchoolID', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('SchoolDiseCode', models.CharField(blank=True, max_length=50, null=True)),
                ('Landline', models.CharField(blank=True, max_length=15, null=True)),
                ('Website', models.CharField(blank=True, max_length=100, null=True)),
                ('ESTDate', models.DateField(blank=True, null=True)),
                ('History', models.CharField(blank=True, max_length=2000, null=True)),
                ('GSTNo', models.CharField(blank=True, max_length=50, null=True)),
                ('PanNo', models.CharField(blank=True, max_length=50, null=True)),
                ('RegistrationNo', models.CharField(blank=True, max_length=50, null=True)),
                ('InstitutionCode', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedAt', models.DateTimeField(blank=True, null=True)),
                ('UpdatedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CBSESchool',
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CBSESchoolStaff',
            fields=[
                ('SchoolStaffID', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('DOB', models.DateField()),
                ('TemporaryAddressLine1', models.CharField(blank=True, max_length=50, null=True)),
                ('TemporaryAddressLine2', models.CharField(blank=True, max_length=50, null=True)),
                ('PermanentAddressLine1', models.CharField(blank=True, max_length=50, null=True)),
                ('PermanentAddressLine2', models.CharField(blank=True, max_length=50, null=True)),
                ('WhatsappNo', models.CharField(blank=True, max_length=15, null=True)),
                ('DateOfAppointment', models.DateField(blank=True, null=True)),
                ('DateOfRetirement', models.DateField(blank=True, null=True)),
                ('ProvidentFund', models.BooleanField(blank=True, null=True)),
                ('ESI', models.BooleanField(blank=True, null=True)),
                ('ProfessionalTax', models.BooleanField(blank=True, null=True)),
                ('Gratuity', models.BooleanField(blank=True, null=True)),
                ('CautionDeposit', models.BooleanField(blank=True, null=True)),
                ('ProfileImage', models.CharField(blank=True, max_length=300, null=True)),
                ('AppToken', models.CharField(blank=True, max_length=300, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('AccountNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('AdhaarNo', models.CharField(blank=True, max_length=25, null=True)),
                ('BankAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('BranchName', models.CharField(blank=True, max_length=25, null=True)),
                ('FatherMobileNo', models.CharField(blank=True, max_length=25, null=True)),
                ('FatherName', models.CharField(blank=True, max_length=25, null=True)),
                ('IFSCCode', models.CharField(blank=True, max_length=25, null=True)),
                ('MotherMobileNo', models.CharField(blank=True, max_length=25, null=True)),
                ('MotherName', models.CharField(blank=True, max_length=25, null=True)),
                ('PanNo', models.CharField(blank=True, max_length=25, null=True)),
                ('PassportNo', models.CharField(blank=True, max_length=25, null=True)),
                ('SpouseMobileNo', models.CharField(blank=True, max_length=25, null=True)),
                ('SpouseName', models.CharField(blank=True, max_length=25, null=True)),
                ('PlaceOfBirth', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedAt', models.DateTimeField(blank=True, null=True)),
                ('UpdatedAt', models.DateTimeField(blank=True, null=True)),
                ('StaffCode', models.IntegerField(blank=True, null=True)),
                ('FirebaseToken', models.CharField(blank=True, max_length=500, null=True)),
                ('IsLoggedIn', models.BooleanField(default=False)),
                ('SchoolID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.cbseschool')),
            ],
            options={
                'db_table': 'CBSESchoolStaff',
            },
        ),
        migrations.CreateModel(
            name='FineSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('Staff', 'Staff'), ('Student', 'Student'), ('Visitor', 'Visitor')], max_length=50)),
                ('no_of_days', models.PositiveIntegerField()),
                ('fine_amt', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('book_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.book_type')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('library_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('number_card', models.CharField(max_length=100)),
                ('membership_type', models.CharField(choices=[('Part_Time', 'Part_Time'), ('Teaching', 'Teaching'), ('Non_Teaching', 'Non_Teaching')], max_length=255)),
                ('Department', models.CharField(choices=[('Civil', 'Civil'), ('IT', 'IT'), ('Software', 'Software'), ('Management', 'Management')], max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('school_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.cbseschool')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('Photo', models.CharField(max_length=100)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('BirthPlace', models.CharField(blank=True, max_length=50, null=True)),
                ('IdentificationMark', models.CharField(blank=True, max_length=50, null=True)),
                ('AdhaarNo', models.CharField(blank=True, max_length=50, null=True)),
                ('PassportNo', models.CharField(blank=True, max_length=50, null=True)),
                ('MedicalCondition', models.CharField(blank=True, max_length=250, null=True)),
                ('PermanentAddressLine1', models.CharField(blank=True, max_length=100, null=True)),
                ('PermanentAddressLine2', models.CharField(blank=True, max_length=100, null=True)),
                ('TemporaryAddressLine1', models.CharField(blank=True, max_length=100, null=True)),
                ('TemporaryAddressLine2', models.CharField(blank=True, max_length=100, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('PanCardNo', models.CharField(blank=True, max_length=25, null=True)),
                ('VoterID', models.CharField(blank=True, max_length=25, null=True)),
                ('PreviousSchoolName', models.CharField(blank=True, max_length=50, null=True)),
                ('PrevSchoolDiseCode', models.CharField(blank=True, max_length=50, null=True)),
                ('TransferCertificateNo', models.CharField(blank=True, max_length=50, null=True)),
                ('SATSNo', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedAt', models.DateTimeField(blank=True, null=True)),
                ('UpdatedAt', models.DateTimeField(blank=True, null=True)),
                ('AdmissionNo', models.CharField(blank=True, max_length=100, null=True)),
                ('AdmissionDate', models.DateField(blank=True, null=True)),
                ('SchoolID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.cbseschool')),
            ],
            options={
                'db_table': 'CBSESchoolStudents',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('accession_number', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('translator', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('volume', models.CharField(max_length=25)),
                ('call_number', models.CharField(blank=True, max_length=20)),
                ('published_year', models.PositiveIntegerField()),
                ('published_place', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('page_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('UnAvailable', 'UnAvailable')], max_length=255)),
                ('isbn', models.CharField(max_length=13)),
                ('date', models.DateField()),
                ('bill_number', models.PositiveIntegerField()),
                ('bill_date', models.DateField()),
                ('book_image', models.ImageField(blank=True, upload_to='book_images/')),
                ('book_summary', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_written', to='lms.author')),
                ('co_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_coauthored', to='lms.author')),
                ('book_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.book_type')),
                ('school_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.cbseschool')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.editor')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.language')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.location')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.publisher')),
                ('remarks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.remark')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.subject')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.book')),
                ('school_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.cbseschool')),
                ('staff', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lms.staff')),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lms.student')),
            ],
        ),
        migrations.CreateModel(
            name='CollectFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fine', models.PositiveIntegerField()),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('fine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.finesetting')),
                ('transction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('Referred_by', models.CharField(max_length=255)),
                ('Referrer_phone', models.CharField(blank=True, max_length=20)),
                ('membership_type', models.CharField(choices=[('Guest_Visistor', 'Guest_Visistor')], max_length=255)),
                ('visit_type', models.CharField(choices=[('Principal', 'Principal'), ('Teacher', 'Teacher'), ('Chairman', 'Chairman')], max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('school_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.cbseschool')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='visitor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lms.visitor'),
        ),
    ]
