# Generated by Django 5.0.4 on 2024-04-07 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('library_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('number_card', models.IntegerField()),
                ('membership_type', models.CharField(choices=[('Part_Time', 'Part Time'), ('Teaching', 'Teaching'), ('Non_Teaching', 'Non Teaching')], max_length=255)),
                ('Department', models.CharField(choices=[('Civil', 'Civil'), ('IT', 'IT'), ('Software', 'Software'), ('Management', 'Management')], max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('Referred_by', models.CharField(max_length=255)),
                ('Referrer_phone', models.CharField(blank=True, max_length=20)),
                ('membership_type', models.CharField(choices=[('Guest_Visistor', 'Guest_Visistor')], max_length=255)),
                ('visit_type', models.CharField(choices=[('Principal', 'Principal'), ('Teacher', 'Teacher'), ('Chairman', 'Chairman')], max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FineSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('Staff', 'Staff'), ('Student', 'Student'), ('Visitor', 'Visitor')], max_length=50)),
                ('no_of_days', models.PositiveIntegerField()),
                ('fine_amt', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('book_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.book_type')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('accession_number', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('translator', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('volume', models.CharField(max_length=25)),
                ('copies', models.PositiveIntegerField()),
                ('call_number', models.CharField(blank=True, max_length=20)),
                ('published_year', models.PositiveIntegerField()),
                ('published_place', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('page_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('UnAvailable', 'UnAvailable')], max_length=255)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('date', models.DateField()),
                ('bill_number', models.PositiveIntegerField()),
                ('bill_date', models.DateField()),
                ('book_image', models.ImageField(blank=True, upload_to='book_images/')),
                ('desc', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_written', to='lms.author')),
                ('co_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_coauthored', to='lms.author')),
                ('book_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.book_type')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.editor')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.language')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.location')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.publisher')),
                ('remarks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.remark')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.subject')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_id', models.PositiveIntegerField()),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.book')),
                ('borrower_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
