# Generated by Django 5.0.4 on 2024-04-07 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='borrower_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('staff', 'student', 'visitor')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='CollectFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fine', models.PositiveIntegerField()),
                ('fine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.finesetting')),
                ('transction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.transaction')),
            ],
        ),
    ]
