# Generated by Django 5.0.4 on 2024-04-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_delete_borrower_alter_author_id_alter_book_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Photo',
            field=models.ImageField(blank=True, upload_to='student_images/'),
        ),
    ]
