# Generated by Django 5.0.4 on 2024-04-17 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.cbseschool'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.staff'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.student'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.visitor'),
        ),
    ]
