# Generated by Django 5.0.4 on 2024-04-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_author_name_alter_book_type_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_barcode_image',
            field=models.ImageField(blank=True, upload_to='book_barcode_images/'),
        ),
    ]
