# Generated by Django 5.0.4 on 2024-04-17 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_transaction_school_id_alter_transaction_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.cbseschool'),
        ),
        migrations.AddField(
            model_name='book_type',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.cbseschool'),
        ),
        migrations.AddField(
            model_name='editor',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.cbseschool'),
        ),
        migrations.AddField(
            model_name='language',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.cbseschool'),
        ),
        migrations.AddField(
            model_name='location',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.cbseschool'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.cbseschool'),
        ),
        migrations.AddField(
            model_name='remark',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.cbseschool'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.cbseschool'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.cbseschool'),
        ),
    ]
