# Generated by Django 5.0.4 on 2024-04-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_book_book_barcode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='number_card',
            field=models.CharField(max_length=100),
        ),
    ]
