# Generated by Django 5.0.4 on 2024-04-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_staff_number_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='membership_type',
            field=models.CharField(choices=[('Part_Time', 'Part_Time'), ('Teaching', 'Teaching'), ('Non_Teaching', 'Non_Teaching')], max_length=255),
        ),
    ]
