# Generated by Django 5.0.4 on 2024-04-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_author_school_id_book_type_school_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
