# Generated by Django 5.0.4 on 2024-04-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='issue_type',
            field=models.CharField(choices=[('New', 'New'), ('Old', 'Old')], max_length=100, null=True),
        ),
    ]
